# Generated by Django 6.0.1 on 2026-02-08 10:02

from django.db import migrations

VIEW_SQL = """
CREATE VIEW author_news_stats AS
SELECT
    a.id AS author_id,
    a.first_name,
    a.last_name,
    a.death_date IS NULL AS is_alive,

    COUNT(n.id) AS news_count,
    COUNT(n.id) FILTER (WHERE n.is_published) AS published_news_count,
    MAX(n.pub_date) AS last_pub_date,

    GROUP_CONCAT(DISTINCT at.name) AS author_tags,
    GROUP_CONCAT(DISTINCT nt.name) AS news_tags

FROM news_author a
LEFT JOIN news_news n ON n.author_id = a.id

LEFT JOIN news_author_tags at_rel ON at_rel.author_id = a.id
LEFT JOIN news_tag at ON at.id = at_rel.tag_id

LEFT JOIN news_news_tags nt_rel ON nt_rel.news_id = n.id
LEFT JOIN news_tag nt ON nt.id = nt_rel.tag_id

GROUP BY a.id, a.first_name, a.last_name, a.death_date;

"""

DROP_VIEW_SQL = """DROP VIEW author_news_stats;"""

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_tag_author_tags_news_tags'),
    ]

    operations = [
        migrations.RunSQL(VIEW_SQL, DROP_VIEW_SQL),
    ]
