# Generated by Django 6.0.1 on 2026-02-08 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_create_author_news_stats_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorNewsStats',
            fields=[
                ('author', models.OneToOneField(db_column='author_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='stats', serialize=False, to='news.author')),
                ('is_alive', models.BooleanField()),
                ('news_count', models.IntegerField()),
                ('published_news_count', models.IntegerField()),
                ('last_pub_date', models.DateTimeField()),
                ('author_tags', models.TextField()),
                ('news_tags', models.TextField()),
            ],
            options={
                'db_table': 'author_news_stats',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Publication date'),
        ),
    ]
