# Generated by Django 6.0.1 on 2026-02-08 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Keep the view SQL local to avoid import-time coupling between migrations.
VIEW_SQL = """
CREATE VIEW author_news_stats AS
SELECT
    a.id AS author_id,
    a.first_name,
    a.last_name,
    a.death_date IS NULL AS is_alive,

    COUNT(n.id) AS news_count,
    COUNT(n.id) FILTER (WHERE n.is_published) AS published_news_count,
    MAX(n.pub_date) AS last_pub_date,

    GROUP_CONCAT(DISTINCT at.name) AS author_tags,
    GROUP_CONCAT(DISTINCT nt.name) AS news_tags

FROM news_author a
LEFT JOIN news_news n ON n.author_id = a.id

LEFT JOIN news_author_tags at_rel ON at_rel.author_id = a.id
LEFT JOIN news_tag at ON at.id = at_rel.tag_id

LEFT JOIN news_news_tags nt_rel ON nt_rel.news_id = n.id
LEFT JOIN news_tag nt ON nt.id = nt_rel.tag_id

GROUP BY a.id, a.first_name, a.last_name, a.death_date;

"""

DROP_VIEW_SQL = """DROP VIEW IF EXISTS author_news_stats;"""


def null_orphan_news_authors(apps, schema_editor):
    News = apps.get_model('news', 'News')
    Author = apps.get_model('news', 'Author')

    existing_author_ids = Author.objects.values_list('id', flat=True)
    News.objects.exclude(author_id__in=existing_author_ids).update(author_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_authornewsstats_alter_news_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(DROP_VIEW_SQL, migrations.RunSQL.noop),
        migrations.RunPython(null_orphan_news_authors, migrations.RunPython.noop),
        migrations.AddField(
            model_name='author',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='authors', to='news.tag'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news', to='news.tag'),
        ),
        migrations.RunSQL(VIEW_SQL, DROP_VIEW_SQL),
    ]
