
### Snippets

GET http://127.0.0.1:8000/api/snippets/

###

POST http://127.0.0.1:8000/api/snippets/

{
    "title": "ABC",
    "code": "1 + 1 == 3",
    "language": "java"
}

###

GET http://127.0.0.1:8000/api/snippets/1


###

PUT http://127.0.0.1:8000/api/snippets/1/

{
    "code": "y=1",
    "linenos": true
}

###

DELETE http://127.0.0.1:8000/api/snippets/1/

### Books

GET http://127.0.0.1:8000/api/books/


###

POST http://127.0.0.1:8000/api/books/

{
    "title": "ABC",
    "author": "Xyz"
}