# Generated by Django 6.0.1 on 2026-02-21 16:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=40)),
                ('captured_at', models.DateTimeField()),
                ('available_qty', models.IntegerField()),
                ('reserved_qty', models.IntegerField(default=0)),
                ('warehouse_code', models.CharField(max_length=32)),
            ],
            options={
                'indexes': [models.Index(fields=['sku', '-captured_at'], name='inventory_sku_captured_idx'), models.Index(fields=['warehouse_code'], name='inventory_wh_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('available_qty__gte', 0)), name='inventory_available_non_negative'), models.CheckConstraint(condition=models.Q(('reserved_qty__gte', 0)), name='inventory_reserved_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('country_code', models.CharField(max_length=2)),
                ('source_system_id', models.CharField(default='PIM', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='catalog.tag')),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='category_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='uniq_category_name_parent'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku', 'country_code'], name='product_sku_country_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['source_system_id'], name='product_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', Decimal('0'))), name='product_price_non_negative'),
        ),
    ]
