# Generated by Django 6.0.1 on 2026-02-21 16:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('country_code', models.CharField(max_length=2)),
                ('source_system_id', models.CharField(default='CRM', max_length=40)),
            ],
            options={
                'indexes': [models.Index(fields=['country_code', 'name'], name='org_country_name_idx'), models.Index(fields=['source_system_id'], name='org_source_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'country_code'), name='uniq_organization_name_country')],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('country_code', models.CharField(max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('source_system_id', models.CharField(default='CRM', max_length=40)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='people.person')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='people.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateField(auto_now_add=True)),
                ('source_system_id', models.CharField(default='IAM', max_length=40)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.role')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(related_name='people', through='people.PersonRole', to='people.role'),
        ),
        migrations.AddIndex(
            model_name='personrole',
            index=models.Index(fields=['source_system_id'], name='person_role_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='personrole',
            constraint=models.UniqueConstraint(fields=('person', 'role', 'organization'), name='uniq_person_role_org'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['country_code', 'email'], name='person_country_email_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['source_system_id'], name='person_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('email__contains', '@')), name='person_email_contains_at'),
        ),
    ]
