# Generated by Django 6.0.1 on 2026-02-07 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modele.person')),
                ('hire_date', models.DateField(null=True)),
                ('bio', models.TextField(null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('contract_type', models.CharField(choices=[('full', 'Full-time'), ('part', 'Part-time')], max_length=5, null=True)),
            ],
            bases=('modele.person',),
        ),
    ]
