# Generated by Django 6.0.1 on 2026-02-07 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modele', '0003_person_created_at_person_updated_at_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='chair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='modele.instructor'),
        ),
    ]
