# Generated by Django 6.0.1 on 2026-02-07 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modele', '0004_alter_department_chair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modele.person')),
                ('enrollment_date', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('modele.person',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('level', models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], max_length=10)),
                ('max_students', models.PositiveIntegerField(default=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modele.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modele.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modele.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='modele.Enrollment', to='modele.student'),
        ),
    ]
