# Generated by Django 6.0.1 on 2026-02-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modele', '0005_student_course_enrollment_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
