# Generated by Django 6.0.1 on 2026-02-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modele', '0006_alter_enrollment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', through='modele.Enrollment', to='modele.student'),
        ),
    ]
