# Generated by Django 6.0.1 on 2026-02-21 16:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('order_placed', 'Order Placed'), ('payment_updated', 'Payment Updated'), ('profile_updated', 'Profile Updated')], max_length=32)),
                ('happened_at', models.DateTimeField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('country_code', models.CharField(default='US', max_length=2)),
                ('source_system_id', models.CharField(default='TRACKER', max_length=40)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['actor_email', 'happened_at'], name='event_actor_happened_idx'), models.Index(fields=['event_type', 'happened_at'], name='event_type_happened_idx'), models.Index(fields=['source_system_id'], name='event_source_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('actor_email', ''), ('actor_email__contains', '@'), _connector='OR'), name='event_actor_email_blank_or_email')],
            },
        ),
    ]
